title: Términos
description: Aquí escribo lo que aprendo en el día a día. 

url: "http://jonathanduarte.rocks/Terminos"
baseurl: "http://jonathanduarte.rocks/Terminos"
# baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Programación
    url: /index.html

social:
  github: jonathanduarte
  email: mrduarte55@gmail.com
  twitter: jodayc055
