title: Electiva V
description: Electiva 5

url: "http://jonathanduarte.rocks/redes"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Redes
    url: /index.html
  - title: Comunicaciones
    url: /comunication
  - title: Datos
    url: /dates

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

collections:
  conicaciones:
    output: true
  datos:
    output: true
